class Intents:
    RUN = "Run"
    FIGHT = "Fight"
    UNKNOWN = "Unknown"
    BACK = "Back"
    START = "Start"
    UP = "Up"
    DIR_N_STEPS = "Direction number steps"
    DOWN = "Down"
    LEFT = "Left"
    RIGHT = "Right"
    GO = "Go"
    NO = "No"
    QUIT = "Quit"